### ISSUE TITLE
404: link invalid

### ISSUE THREAD

**Issue by utkarsh2102** [suntong/dbab#1]
Hi,
While reviewing dbab, I came across this line which points to an invalid link.

https://github.com/suntong/dbab/blob/5f4ba25406547596fd39406673774d93b06a8e07/assets/dbab.service#L7

Could you please look at it and fix the same? :)

**Comment by suntong** [comment]
(Forgot to close)
Fixed in https://github.com/suntong/dbab/commit/57c469be52e24c5d51b915150b08f27dc91a3eda#diff-54d314843daf2f49f0f02aa1e16c0292fd9fe699813b2e888ee66aeda3a4675f
