### ISSUE TITLE
Improvement: filtering using iptables / ipfilter firewall ?

### ISSUE THREAD

**Issue by pms967** [suntong/dbab#3]
First of all, thank you for your great software. I use and like it a lot.

Coming to the question: dbab works great, but it may be circumvented if a site use IPs instead of names. What about adding support for (optional) IP filtering using firewall rules, too?

Tnx for your attention.

**Comment by suntong** [comment]
Hi, 

After careful evaluation the situation, I have to conclude the issue to the "wontfix" category as I have never noticed such problem before. I'm not saying it doesn't exist, but I'm saying that it is so rare that the payoff doing so is minimum. 

I'd suggest to try [`dbab-add-list`](https://github.com/suntong/dbab#dbab-add-list) to see if it works with IP as well. 

Else, if you come up with a solution, I'd be happy to link to your solution from dbab. 

Thanks again for using dbab and reporting problems.
