### ISSUE TITLE
Incorrect URL in /usr/sbin/dbab-get-list, has moved from http:: to https::

### ISSUE THREAD

**Issue by chrisisbd** [suntong/dbab#8]
I just installed dbab on my Raspberry Pi DHCP/DNS server.

The dnsmasq server failed to restart because the file /etc/dnsmasq.d/dbab.adblock.conf contained an error rather than
dnsmasq configuration options.

The error was simply that the server list has moved from
http://pgl.yoyo.org/adservers/serverlist.php to https://pgl.yoyo.org/adservers/serverlist.php

I have simply edited the /usr/sbin/dbab-get-list script to fix the problem, change http:: to https::

**Comment by suntong** [comment]
Are you reporting the same issue as https://github.com/suntong/dbab/issues/2 @chrisisbd?

**Comment by chrisisbd** [comment]
No, I don't think so.  The error I have reported means that dnsmasq fails to start after installing dbad because the file /etc/dnsmasq.d/dbab.adblock.conf has an error message from curl in it rather than a list of web sites.

**Comment by chrisisbd** [comment]
It *may* be the same error but it's certainly not fixed in dbab 1.3.2 on Raspberry Pi.  Using the http:// URL produces an error, it doesn't get redirected to https://.

**Comment by suntong** [comment]
- I don't use/know Raspberry Pi
- please check the latest release at https://packages.debian.org/bullseye/dbab
- please follow the bug-reporting template next time when reporting any issues

thanks
